dbt_project:        # <- ce nom doit correspondre à 'name:' dans ton dbt_project.yml
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "MMIWCNH-SV47739"
      user: "GUILLAUMEDMR"
      password: "!Snowflake2025"
      role: "ACCOUNTADMIN"
      warehouse: "COMPUTE_WH"
      database: GOOD_AIR           # base brute
      schema: PUBLIC          # schema par defaut de sortie dbt (redirection silver et gold dans dbt_project.yml et macro generate_schema_name.sql)
      threads: 4
      client_session_keep_alive: false
