dbt_project:        # <- ce nom doit correspondre à 'name:' dans ton dbt_project.yml
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "VUZNAWR-IW20193"
      user: "GUILLAUME"
      password: "!Snowflake2025"
      role: "ACCOUNTADMIN"
      warehouse: "COMPUTE_WH"
      database: GOOD_AIR           # base brute
      schema: SILVER          # schema de sortie dbt
      threads: 4
      client_session_keep_alive: false
