global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-exporter:9112']