name: 'dbt_project'
version: '1.0.0'
config-version: 2

# Lien vers le profiles.yml
profile: 'dbt_project'

# Chemins des dossiers
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

#log pour monitoring
on-run-end:
  - "{{ log_dbt_results(results) }}"

models:
  # Ce nom DOIT être strictement identique au 'name:' de la ligne 1
  dbt_project:

  
    # Configuration pour le dossier models/silver
    silver:
      +schema: SILVER
 
    # Configuration pour le dossier models/gold
    gold:
      +schema: GOLD
