{{
  config(
    materialized='incremental',
    unique_key=['CITY_ID', 'DT_HOUR'],
    incremental_strategy='merge'
  )
}}

WITH BASE_DATA AS (
    SELECT 
        w.CITY_ID,
        -- On crée l'alias DT_HOUR ici pour le reste du modèle Gold
        DATE_TRUNC('hour', w.dt_paris) as DT_HOUR, 
        w.TEMPERATURE,
        w.HUMIDITY,
        w.WIND_SPEED,
        a.AQI,
        (a.AQI * 0.7) + 
        (CASE WHEN w.TEMPERATURE < 5 THEN 20 WHEN w.TEMPERATURE > 32 THEN 15 ELSE 0 END) + 
        (CASE WHEN w.HUMIDITY > 80 THEN 10 ELSE 0 END) as CURRENT_HEALTH_RISK_SCORE
    FROM SILVER.FACT_WEATHER_RECORDS w
    JOIN SILVER.FACT_AIR_QUALITY_RECORDS a 
        ON w.city_id = a.city_id 
        AND DATE_TRUNC('hour', w.dt_paris) = a.dt_paris

    {% if is_incremental() %}
    -- On filtre w.dt_paris (source) par rapport au max de DT_HOUR (destination)
    -- On utilise COALESCE pour le tout premier run
    WHERE w.dt_paris >= (
        SELECT COALESCE(DATEADD('hour', -48, MAX(DT_HOUR)), '2020-01-01') 
        FROM {{ this }}
    )
    {% endif %}
)

SELECT 
    *,
    -- LAGS (Passé)
    LAG(CURRENT_HEALTH_RISK_SCORE, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as RISK_SCORE_LAG_12,
    LAG(TEMPERATURE, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as TEMP_LAG_12,
    LAG(HUMIDITY, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as HUM_LAG_12,
    LAG(WIND_SPEED, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as WIND_LAG_12,
    LAG(AQI, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as AQI_LAG_12,

    LAG(CURRENT_HEALTH_RISK_SCORE, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as RISK_SCORE_LAG_24,
    LAG(TEMPERATURE, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as TEMP_LAG_24,
    LAG(HUMIDITY, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as HUM_LAG_24,
    LAG(WIND_SPEED, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as WIND_LAG_24,
    LAG(AQI, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as AQI_LAG_24,
    
    LAG(CURRENT_HEALTH_RISK_SCORE, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as RISK_SCORE_LAG_48,
    LAG(TEMPERATURE, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as TEMP_LAG_48,
    LAG(HUMIDITY, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as HUM_LAG_48,
    LAG(WIND_SPEED, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as WIND_LAG_48,
    LAG(AQI, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as AQI_LAG_48,

    -- LEADS (Futur)
    LEAD(CURRENT_HEALTH_RISK_SCORE, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as RISK_SCORE_LEAD_12,
    LEAD(TEMPERATURE, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as TEMP_LEAD_12,
    LEAD(HUMIDITY, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as HUM_LEAD_12,
    LEAD(WIND_SPEED, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as WIND_LEAD_12,
    LEAD(AQI, 12) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as AQI_LEAD_12,

    LEAD(CURRENT_HEALTH_RISK_SCORE, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as RISK_SCORE_LEAD_24,
    LEAD(TEMPERATURE, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as TEMP_LEAD_24,
    LEAD(HUMIDITY, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as HUM_LEAD_24,
    LEAD(WIND_SPEED, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as WIND_LEAD_24,
    LEAD(AQI, 24) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as AQI_LEAD_24,

    LEAD(CURRENT_HEALTH_RISK_SCORE, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as RISK_SCORE_LEAD_48,
    LEAD(TEMPERATURE, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as TEMP_LEAD_48,
    LEAD(HUMIDITY, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as HUM_LEAD_48,
    LEAD(WIND_SPEED, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as WIND_LEAD_48,
    LEAD(AQI, 48) OVER (PARTITION BY CITY_ID ORDER BY DT_HOUR) as AQI_LEAD_48

FROM BASE_DATA
ORDER BY CITY_ID, DT_HOUR